FROM microsoft/dotnet:3.0-aspnetcore-runtime-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:3.0-sdk-stretch AS build
WORKDIR /src
COPY ["CellServiceProvider/CellServiceProvider.csproj", "CellServiceProvider/"]
RUN dotnet restore "CellServiceProvider/CellServiceProvider.csproj"
COPY . .
WORKDIR "/src/CellServiceProvider"
RUN dotnet build "CellServiceProvider.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CellServiceProvider.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CellServiceProvider.dll"]